name: CI

on: [push]

inputs:
  test:
    description: 'Number of test'
    required: true
    default: '42'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo $INPUT_TEST
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo $test > oui.txt
        cat oui.txt
